name: Static Analysis

# Run on all push and pull requests
on:
  push:
  pull_request:

jobs:

  static-analysis:
    name: Run cppcheck
    uses: arielswalker/cFS/.github/workflows/static-analysis.yml@test-static-analysis
